CREATE TABLE IF NOT EXISTS PAYMENT
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    BANK_CODE   VARCHAR(50),
    BANK_TRANSACTION_NO   VARCHAR(50),
    PAY_DATE    VARCHAR(50),
    TRANSACTION_STATUS varchar(50),
    PAYMENT_CODE varchar(50),
    USER_ID     BIGINT DEFAULT TRUE,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);