CREATE TABLE IF NOT EXISTS CHAT
(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE IF NOT EXISTS USERS_IN_CHAT
(
    CHAT_ID BIGINT,
    USER_ID BIGINT,
    PRIMARY KEY (CHAT_ID, USER_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    FOREIGN KEY (CHAT_ID) REFERENCES CHAT (ID)
);

CREATE TABLE IF NOT EXISTS MESSAGE
(
    ID        BIGINT PRIMARY KEY AUTO_INCREMENT,
    CONTENT   VARCHAR(1000),
    DATE_SEND DATETIME,
    USER_ID   BIGINT,
    CHAT_ID   BIGINT,
    FOREIGN KEY (CHAT_ID) REFERENCES CHAT (ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);