CREATE TABLE IF NOT EXISTS SEASON
(
    ID           BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME         VARCHAR(50),
    TVSERIES_ID  BIGINT,
    IS_RELEASE   BOOLEAN DEFAULT TRUE,
    DATE_RELEASE DATE,
    FOREIGN KEY (TVSERIES_ID) REFERENCES TVSERIES (ID)
);

CREATE TABLE IF NOT EXISTS EPISODE
(
    ID           BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME         VARCHAR(50),
    SEASON_ID    BIGINT,
    IS_RELEASE   BOOLEAN DEFAULT TRUE,
    DATE_RELEASE DATE,
    URL          VARCHAR(500),
    FOREIGN KEY (SEASON_ID) REFERENCES SEASON (ID)
);

CREATE TABLE IF NOT EXISTS HISTORY_MOVIE
(
    ID       BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID  BIGINT,
    MOVIE_ID BIGINT,
    DURATION FLOAT,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE (ID)
);

CREATE TABLE IF NOT EXISTS HISTORY_EPISODE
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID    BIGINT,
    EPISODE_ID BIGINT,
    DURATION   FLOAT,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    FOREIGN KEY (EPISODE_ID) REFERENCES EPISODE (ID)
);

CREATE TABLE IF NOT EXISTS FAVORITE_MOVIE
(
    USER_ID  BIGINT,
    MOVIE_ID BIGINT,
    PRIMARY KEY (USER_ID, MOVIE_ID)
);

CREATE TABLE IF NOT EXISTS FAVORITE_TVSERIES
(
    USER_ID     BIGINT,
    TVSERIES_ID BIGINT,
    PRIMARY KEY (USER_ID, TVSERIES_ID)
);









