CREATE TABLE IF NOT EXISTS TVSERIES
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME        VARCHAR(50)  NOT NULL,
    DESCRIPTION VARCHAR(50)  NOT NULL,
    YEAR        DATE,
    IMDB        FLOAT        NOT NULL,
    IMAGE       VARCHAR(100) NOT NULL,
    TRAILER     VARCHAR(100) NOT NULL,
    IS_RELEASE BOOLEAN DEFAULT TRUE,
    DATE_RELEASE DATE
);

CREATE TABLE IF NOT EXISTS SEASON
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME        VARCHAR(50) NOT NULL,
    TVSERIES_ID BIGINT      NOT NULL,
    FOREIGN KEY (TVSERIES_ID) REFERENCES TVSERIES (ID)
);

CREATE TABLE IF NOT EXISTS EPISODE
(
    ID        BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME      VARCHAR(50)  NOT NULL,
    VIDEO     VARCHAR(100) NOT NULL,
    SEASON_ID BIGINT       NOT NULL,
    IS_RELEASE BOOLEAN DEFAULT TRUE,
    DATE_RELEASE DATE,
    FOREIGN KEY (SEASON_ID) REFERENCES SEASON (ID),
);

CREATE TABLE IF NOT EXISTS HISTORY_MOVIE
(
    USER_ID  BIGINT NOT NULL,
    MOVIE_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, MOVIE_ID)
);

CREATE TABLE IF NOT EXISTS HISTORY_TVSERIES
(
    USER_ID     BIGINT NOT NULL,
    TVSERIES_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, TVSERIES_ID)
);

CREATE TABLE IF NOT EXISTS HISTORY_EPISODE
(
    USER_ID     BIGINT NOT NULL,
    TVSERIES_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, TVSERIES_ID)
);

CREATE TABLE IF NOT EXISTS FAVORITE_MOVIE
(
    USER_ID     BIGINT NOT NULL,
    MOVIE_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, MOVIE_ID)
);

CREATE TABLE IF NOT EXISTS FAVORITE_TVSERIES
(
    USER_ID     BIGINT NOT NULL,
    TVSERIES_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, TVSERIES_ID)
);









