CREATE TABLE IF NOT EXISTS SEASON
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME        VARCHAR(50) ,
    TVSERIES_ID BIGINT      ,
    IS_RELEASE BOOLEAN DEFAULT TRUE,
    DATE_RELEASE DATE,
    FOREIGN KEY (TVSERIES_ID) REFERENCES TVSERIES (ID)
);

CREATE TABLE IF NOT EXISTS EPISODE
(
    ID        BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME      VARCHAR(50)  ,
    SEASON_ID BIGINT       ,
    IS_RELEASE BOOLEAN DEFAULT TRUE,
    DATE_RELEASE DATE,
    URL VARCHAR(100),
    FOREIGN KEY (SEASON_ID) REFERENCES SEASON (ID)
);

CREATE TABLE IF NOT EXISTS HISTORY_MOVIE
(
    USER_ID  BIGINT ,
    MOVIE_ID BIGINT ,
    PRIMARY KEY (USER_ID, MOVIE_ID)
);

CREATE TABLE IF NOT EXISTS HISTORY_TVSERIES
(
    USER_ID     BIGINT ,
    TVSERIES_ID BIGINT ,
    PRIMARY KEY (USER_ID, TVSERIES_ID)
);

CREATE TABLE IF NOT EXISTS HISTORY_EPISODE
(
    USER_ID     BIGINT ,
    TVSERIES_ID BIGINT ,
    PRIMARY KEY (USER_ID, TVSERIES_ID)
);

CREATE TABLE IF NOT EXISTS FAVORITE_MOVIE
(
    USER_ID     BIGINT ,
    MOVIE_ID BIGINT ,
    PRIMARY KEY (USER_ID, MOVIE_ID)
);

CREATE TABLE IF NOT EXISTS FAVORITE_TVSERIES
(
    USER_ID     BIGINT ,
    TVSERIES_ID BIGINT ,
    PRIMARY KEY (USER_ID, TVSERIES_ID)
);









