ALTER TABLE MOVIE
    ADD IS_RELEASE BOOLEAN DEFAULT TRUE;
ALTER TABLE MOVIE
    ADD DATE_RELEASE DATE;

CREATE TABLE IF NOT EXISTS CATEGORY_TVSERIES
(
    CATEGORY_ID BIGINT NOT NULL,
    TVSERIES_ID    BIGINT NOT NULL,
    PRIMARY KEY (CATEGORY_ID, TVSERIES_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID),
    FOREIGN KEY (TVSERIES_ID) REFERENCES TVSERIES (ID)
    );