INSERT IGNORE INTO CATEGORY (name)
VALUES ('Action'),
       ('Adventure'),
       ('Animation'),
       ('Comedy'),
       ('Crime'),
       ('Drama'),
       ('Fantasy'),
       ('Horror'),
       ('Mystery'),
       ('Romance'),
       ('Science Fiction'),
       ('Thriller'),
       ('War'),
       ('Documentary'),
       ('Musical'),
       ('Western'),
       ('Biography'),
       ('Family');