INSERT IGNORE INTO MOVIE (NAME, DESCRIPTION, YEAR, DURATION, IMDB)
VALUES ('Oppenheimer',
        'The story of American scientist, J. Robert Oppenheimer, and his role in the development of the atomic bomb.',
        2023, 180, 8.5),
       ('Past Lives',
        'Nora and Hae Sung, two deeply connected childhood friends, are wrested apart after Noras family emigrates from South Korea. Twenty years later, they are reunited for one fateful week as they confront notions of love and destiny.',
        2023, 105, 8),
       ('Killers of the Flower Moon',
        'When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one - until the FBI steps in to unravel the mystery.',
        2023, 206, 8),
       ('Poor Things',
        'The incredible tale about the fantastical evolution of Bella Baxter, a young woman brought back to life by the brilliant and unorthodox scientist Dr. Godwin Baxter.',
        2023, 141, 8.5),
       ('Anatomy of a Fall',
        'A woman is suspected of her husbands murder, and their blind son faces a moral dilemma as the main witness.',
        2023, 151, 7.9),
       ('Spider-Man: Across the Spider-Verse',
        'Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. When the heroes clash on how to handle a new threat, Miles must redefine what it means to be a hero.',
        2023, 140, 8.7),
       ('The Holdovers',
        'A cranky history teacher at a remote prep school is forced to remain on campus over the holidays with a troubled student who has no place to go.',
        2023, 133, 8.4),
       ('Mission: Impossible - Dead Reckoning Part One',
        'Ethan Hunt and his IMF team must track down a dangerous weapon before it falls into the wrong hands.', 2023,
        163, 7.8),
       ('Black Clover: Sword of the Wizard King',
        'In a world where magic is everything, Asta, a boy who was born with no magic, aims to become the "Wizard King" to overcome adversity, prove his power, and keep his oath with his friends.',
        2023, 110, 7.4),
       ('Talk to Me',
        'When a group of friends discover how to conjure spirits using an embalmed hand, they become hooked on the new thrill, until one of them goes too far and unleashes terrifying supernatural forces.',
        2022, 95, 7.2),
       ('Everything Everywhere All at Once',
        'A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes and connecting with the lives she could have led.',
        2022, 139, 7.8),
       ('Top Gun: Maverick',
        'After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUNs elite graduates on a mission that demands the ultimate sacrifice from those chosen to fly it.',
        2022, 130, 8.3),
       ('Boiling Point',
        'Enter the relentless pressure of a restaurant kitchen as a head chef wrangles his team on the busiest day of the year.',
        2021, 92, 7.5),
       ('The Batman',
        'When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the citys hidden corruption and question his familys involvement.',
        2022, 176, 7.8),
       ('The Banshees of Inisherin',
        'Two lifelong friends find themselves at an impasse when one abruptly ends their relationship, with alarming consequences for both of them.',
        2022, 114, 7.7),
       ('Aftersun',
        'Sophie reflects on the shared joy and private melancholy of a holiday she took with her father twenty years earlier. Memories real and imagined fill the gaps between as she tries to reconcile the father she knew with the man she didnt...',
        2022, 102, 7.7),
       ('Glass Onion',
        'Tech billionaire Miles Bron invites his friends for a getaway on his private Greek island. When someone turns up dead, Detective Benoit Blanc is put on the case.',
        2022, 139, 7.1),
       ('Tár',
        'Set in the international world of Western classical music, the film centers on Lydia Tár, widely considered one of the greatest living composer-conductors and the very first female director of a major German orchestra.',
        2022, 158, 7.4),
       ('Doctor Strange in the Multiverse of Madness',
        'The sequel to Doctor Strange (2016) and Spider-Man: No Way Home (2021).', 2022, 130, 7.6),
       ('Thor: Love and Thunder', 'The sequel to Thor: Ragnarok and the fourth movie in the Thor saga.', 2022, 130,
        7.5),
       ('Licorice Pizza',
        'The story of Alana Kane and Gary Valentine growing up, running around and going through the treacherous navigation of first love in the San Fernando Valley, 1973.',
        2021, 133, 7.1),
       ('The French Dispatch',
        'A love letter to journalists set in an outpost of an American newspaper in a fictional twentieth century French city that brings to life a collection of stories published in "The French Dispatch Magazine".',
        2021, 107, 7.1),
       ('The Last Duel',
        'The Knight Jean de Carrouges must settle the dispute over his wife Marguerite by challenging his squire to a duel to the death.',
        2021, 152, 7.4),
       ('Shang-Chi and the Legend of the Ten Rings',
        'Shang-Chi, the master of weaponry-based Kung Fu, is forced to confront his past after being drawn into the Ten Rings organization.',
        2021, 132, 7.4),
       ('Last Night in Soho',
        'Aspiring fashion designer Eloise is mysteriously able to enter the 1960s, where she encounters dazzling wannabe singer Sandie. But the glamour is not as it seems, and the dreams of the past crack and splinter into something darker.',
        2021, 116, 7.0),
       ('King Richard',
        'A look at how tennis superstars Venus and Serena Williams became who they are after the coaching from their father Richard Williams.',
        2021, 144, 7.5),
       ('The Suicide Squad',
        'Supervillains Harley Quinn, Bloodsport, Peacemaker, and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.',
        2021, 132, 7.2),
       ('Free Guy',
        'When Guy, a bank teller, learns that he is a non-player character in a bloodthirsty, open-world video game, he goes on to become the hero of the story and takes the responsibility of saving the world.',
        2021, 115, 7.1),
       ('Dune',
        'A noble family becomes embroiled in a war for control over the galaxy most valuable asset while its heir becomes troubled by visions of a dark future.',
        2021, 155, 8.0),
       ('Spider-Man: No Way Home',
        'With Spider-Man identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.',
        2021, 148, 8.2);


INSERT IGNORE INTO CATEGORY_MOVIE (CATEGORY_ID, MOVIE_ID)
values (1, 1),
       (6, 1),
       (17, 1),
       (1, 2),
       (10, 2),
       (6, 2),
       (1, 3),
       (5, 3),
       (6, 3),
       (4, 4),
       (7, 4),
       (3, 5),
       (1, 5),
       (2, 5),
       (4, 6),
       (6, 6),
       (16, 6),
       (8, 7),
       (9, 7),
       (12, 7),
       (1, 8),
       (2, 8),
       (12, 8),
       (3, 9),
       (1, 9),
       (2, 9),
       (7, 9),
       (8, 10),
       (9, 10),
       (12, 10),
       (1, 11),
       (6, 11),
       (17, 11),
       (1, 12),
       (10, 12),
       (6, 12),
       (1, 13),
       (5, 13),
       (6, 13),
       (4, 14),
       (7, 14),
       (3, 15),
       (1, 15),
       (2, 15),
       (4, 16),
       (6, 16),
       (16, 16),
       (8, 17),
       (9, 17),
       (12, 17),
       (1, 18),
       (2, 18),
       (12, 18),
       (3, 19),
       (1, 19),
       (2, 19),
       (7, 19),
       (8, 20),
       (9, 20),
       (12, 20),
       (4, 21),
       (4, 22),
       (6, 23),
       (1, 24),
       (8, 25),
       (6, 26),
       (1, 27),
       (4, 28),
       (6, 29),
       (1, 30);
