INSERT IGNORE INTO SEASON (NAME, TVSERIES_ID)
VALUES ('Season 1', 1),
       ('Season 2', 1),
       ('Season 1', 2),
       ('Season 2', 2),
       ('Season 1', 3),
       ('Season 2', 3),
       ('Season 1', 4),
       ('Season 2', 4),
       ('Season 1', 5),
       ('Season 2', 5),
       ('Season 1', 6),
       ('Season 2', 6),
       ('Season 1', 7),
       ('Season 2', 7),
       ('Season 1', 8),
       ('Season 2', 8),
       ('Season 1', 9),
       ('Season 2', 9),
       ('Season 1', 10),
       ('Season 2', 10),
       ('Season 1', 11),
       ('Season 2', 11),
       ('Season 1', 12),
       ('Season 2', 12);

INSERT IGNORE INTO EPISODE (NAME, SEASON_ID)
VALUES ('Episode 1', 1),
       ('Episode 2', 1),
       ('Episode 3', 1),
       ('Episode 4', 1),
       ('Episode 1', 2),
       ('Episode 2', 2),
       ('Episode 3', 2),
       ('Episode 4', 2);
