CREATE TABLE IF NOT EXISTS MOVIE_COMMENTS
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    COMMENT     VARCHAR(2000),
    DATE_POST   DATETIME,
    MOVIE_ID    BIGINT,
    USER_ID     BIGINT DEFAULT TRUE,
    TOTAL_LIKES INT,
    FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE (ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE TABLE IF NOT EXISTS MOVIE_SUB_COMMENT
(
    ID                BIGINT PRIMARY KEY AUTO_INCREMENT,
    COMMENT           VARCHAR(2000),
    DATE_POST         DATETIME,
    MOVIE_COMMENTS_ID BIGINT,
    USER_ID           BIGINT DEFAULT TRUE,
    TOTAL_LIKES       INT,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    FOREIGN KEY (MOVIE_COMMENTS_ID) REFERENCES MOVIE_COMMENTS (ID)
);

CREATE TABLE IF NOT EXISTS USER_TAGGED_IN_COMMENT
(
    COMMENT_ID     BIGINT,
    USER_ID_TAGGED BIGINT,
    FOREIGN KEY (COMMENT_ID) REFERENCES MOVIE_COMMENTS (ID),
    FOREIGN KEY (USER_ID_TAGGED) REFERENCES USERS (ID),
    PRIMARY KEY (COMMENT_ID, USER_ID_TAGGED)
);

CREATE TABLE IF NOT EXISTS USER_TAGGED_IN_SUB_COMMENT
(
    SUB_COMMENT_ID             BIGINT,
    USER_TAGGED_IN_SUB_COMMENT BIGINT,
    FOREIGN KEY (SUB_COMMENT_ID) REFERENCES MOVIE_SUB_COMMENT (ID),
    FOREIGN KEY (USER_TAGGED_IN_SUB_COMMENT) REFERENCES USERS (ID),
    PRIMARY KEY (SUB_COMMENT_ID, USER_TAGGED_IN_SUB_COMMENT)
);
