CREATE TABLE IF NOT EXISTS MOVIE_COMMENTS
(
    ID           BIGINT PRIMARY KEY AUTO_INCREMENT,
    COMMENT      VARCHAR(2000),
    DATE_POST    DATE,
    MOVIE_ID     BIGINT,
    USER_ID      BIGINT DEFAULT TRUE,
    FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE (ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE TABLE IF NOT EXISTS REPLIED_COMMENTS_MOVIE
(
    ID           BIGINT PRIMARY KEY AUTO_INCREMENT,
    COMMENT      VARCHAR(2000),
    DATE_POST    DATE,
    MOVIECOMMENTS_ID BIGINT,
    USER_ID      BIGINT DEFAULT TRUE,
    REPLIED_TO_USER_ID BIGINT,
    FOREIGN KEY (REPLIED_TO_USER_ID) REFERENCES USERS (ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);
