CREATE TABLE IF NOT EXISTS USER_LIKE_MOVIE_COMMENT
(
    MOVIE_COMMENT_ID BIGINT,
    USER_ID          BIGINT,
    FOREIGN KEY (MOVIE_COMMENT_ID) REFERENCES MOVIE_COMMENTS (ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    PRIMARY KEY (MOVIE_COMMENT_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS USER_LIKE_MOVIE_SUB_COMMENT
(
    MOVIE_SUB_COMMENT_ID BIGINT,
    USER_ID              BIGINT,
    FOREIGN KEY (MOVIE_SUB_COMMENT_ID) REFERENCES MOVIE_SUB_COMMENT (ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    PRIMARY KEY (MOVIE_SUB_COMMENT_ID, USER_ID)
);

